CREATE TABLE USUARIO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    MATRICULA VARCHAR(13),
    EMAIL VARCHAR(50),
    PHONE VARCHAR(15),
    LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    IMAGEM MEDIUMBLOB,
    ATIVO BOOL DEFAULT TRUE,
    ADMIN BOOL DEFAULT FALSE,
    TECN BOOL DEFAULT FALSE
);

CREATE TABLE CHAMADO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TITULO VARCHAR(30),
    DESCRICAO VARCHAR(100),
    TIPO VARCHAR(25),
    DATA_INICIO TIMESTAMP,
    DATA_FINAL TIMESTAMP,
    BLOCO VARCHAR(1),
    SALA INTEGER,
    STATUS VARCHAR(30),
    IMAGEM MEDIUMBLOB,
    ATIVO BOOL DEFAULT TRUE
    REQUERENTE_ID INTEGER REFERENCES USUARIO (ID),
    TECNICO_ID INTEGER REFERENCES USUARIO (ID)
);

CREATE TABLE USUARIO_CHAMADO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CHAMADO_ID INTEGER REFERENCES CHAMADO (ID),
    USUARIO_ID INTEGER REFERENCES USUARIO (ID)
);